apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleorder
  namespace: tutorial
  labels:
    app: simpleorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleorder
  template:
    metadata:
      labels:
        app: simpleorder
    spec:
      containers:
        - name: simpleorder
          image: hyeonwoos.azurecr.io/simpleorder:v1
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: url
